print("Enter the no of days meet after")
day=int(input())
day=day%7
if(day==0):
    print("Saturday")
if(day==1):
    print("Sunday")
if(day==2):
    print("Monday")
if(day==3):
    print("Tuesday")
if(day==4):
    print("Wednesday")
if(day==5):
    print("Thursday")
if(day==6):
    print("Friday")
if(day==7):
    print("Saturday")